apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yaml: |
    tunnel: {{ .Values.tunnelId }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    metrics: 0.0.0.0:2000
    ingress:
    {{- range .Values.ingress }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
    {{- end }}
      - service: http_status:404
