appApiPostgres:
    password: ENC[AES256_GCM,data:/Z/4rWeTyiMlksFkHNj0Ecu/Ab25WSG/Pq9CokI8JOU=,iv:CJ/MBrG5/vfx9U3FzBJF010jj2g+0vx6nrtMvrVAchI=,tag:k65Gra80+D4QGnGijlXE9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaFJNZ21pL0Q1dFlXdGtW
            STdqNjhoeU9JWk5vdWk3MzluZExmN2pZWWtVCkhaVlZlV05McUlzdnp1UnZWSkV6
            WFRaOGJsL0V5MHpvcWlwTjJjdmpTYUEKLS0tIHkyZ2Q4NStRbFVka1FNQndIRURQ
            eVp6R2VVOU1rQUhkekNPWk1vWVo2emsK1beF4L8VREA+EQ9BP9KzieDfi+eXfSjR
            L9sYL4+f/VfEMWPe+kSyLx23YrtcinOC3ByE5yO1nUAATSfC5UauXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1huxz79cghdf0ewq6mq78pu3wuzyfhdr8qlw45tlqt74xrqt6t3es8k0zw0
    lastmodified: "2026-07-03T01:19:55Z"
    mac: ENC[AES256_GCM,data:kYGfq5ByYlcaMwJ+AzdExbwrkReLcJGkLBwVRLReEJDamgkYHwteIfM8h5V/A8sWzfLyKPG21B+ZPdO0fynd84QVuYflKS5NfGyVsufzeQXN3t2NCGgxEOY+yTncjHMYUEEXQ1ZnZmjgN+ud8T/77b2ln6qm6jusAUbY/U/YlGY=,iv:BVTUro2/6Jw5UvDghpjUYBpIDbbprfZ6b3hKnX/eB0A=,tag:zTbZN5ymptZ96AZtNctLDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
