#ENC[AES256_GCM,data:cZv9exhl5XtuBgnXIJQvaIHCKm4wkpfVFOpYwAI6rMq5wqMNhYmkafabHCoKbSBrJMdD6Q0ATTicK/gYAEtCUMEuXjktXuHjEGLo,iv:jL4UJ39Lejkvm8u4fYydix5xTLjJayfWAeEN6BQeVBw=,tag:MC/kIz8ePIGVCTbmqs6htw==,type:comment]
#ENC[AES256_GCM,data:zSQdMHYGtQvyzUJVYd9X5uDEfHviUbHbXZRaUOi+ZBImXbNIvKY1dwuZm2AgWcH7ovhSk/9lyLZV/GB09srUC6wiK8upGqezZg==,iv:dtgAJ8bIjBQ9tSfaTaY0fXOvLRNqS27duCxf42X3zDE=,tag:Y6Yh94rCVKF0lbGOjRjoNQ==,type:comment]
cloudflared:
    tunnelId: ENC[AES256_GCM,data:XvRK6MxaZNl1zaeRVBWNtKp39gaxnI/1cYFJs/SC88bxKtEL,iv:EbwbC9VGvOu6ELJvBTMjdeiLQfKAsdnykpb+oc/f6cQ=,tag:4yOdmUvASqspyIt8X801iA==,type:str]
    credentialsJson: ENC[AES256_GCM,data:endflIuGZ8W7U6mwEWvyXDgY6cLs0+S2z1bwWOosLYWQVGNX9OEOIgLfYq3aZVNU0Dk7nWy7+CLhoLvyHc3lv9xfBt25gct/XnNc2ilNfbLI/BRwT1n+P8ovOmf9+e7KaGfTi08yodR0CYhxlMggIPC1IQXbv7an8+jJHgxF0fv5fyZuKmBmo/BEweke0FVgQnh3IW4JCWYiAEA1gCQUvNOin3X3UsLqrq85PvPe6g==,iv:NwETK05NW0SKpafOtt8hqYCnxF91wNbn721c9HZ0tZo=,tag:9LdGp3I/fIWa6YGGRmN8Ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaHZFeUY0MWhjMzNzNEVG
            b29lK3VQR29Ray9KZG5TaUJYLzA1VGttTUIwCkFJNCszaGl3Vyt4dHA1VTE0RFJy
            TC9WVUt0UHNiSzNLL3phWGMyK0p5Y2sKLS0tIC94VnNvTDdLQVhyKys3R3d3ZmVH
            SzN6dUZuRUJIYWdGNEdmMnQ0SkZGQXMKq4XinkG+LYLYKos9RNXwRqRU9xCDyiHu
            Gp9xFJpGGJTO9UpPLl0+5c4hT8DCptmGULH6jv69AjOoc6j5IimMxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1huxz79cghdf0ewq6mq78pu3wuzyfhdr8qlw45tlqt74xrqt6t3es8k0zw0
    lastmodified: "2026-07-02T20:10:35Z"
    mac: ENC[AES256_GCM,data:9azkUveoVRlRf2kV1H/+/u4sDP4cSu0zHa7KHqBnLYoTO6bn2QAE6SijJBeCfndZ7icZMJBdj/dfj411Xu5S/uGAdxTSG3c9LqR1KWTk17+I2g08efw8OoWILZ50yxKNcOXq0r9snMHMW/1iP3yd6u8K8UIPGqzhMFH/KQKL7rY=,iv:hmcI6Db/CvL4/nqArrjrwQgx/GzWpbCl49UTVW0jPDg=,tag:73rISN1dlYq/TG38LlvfCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
