password: ENC[AES256_GCM,data:gSS8xPVYF6YXNS7ejbI3yTxB0/AkadKxFYHQxil+euLjYQKU4m10mA==,iv:WqKG4ISzoTsAO69sZ59+ATSxyDGHDuY8IQ24xB9Sv4Q=,tag:dW7nWmgR4IXuu7T5vKCsNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbUVuOTE4OU1zVlcvYTY0
            cXNrREJuRzRXb1EwZW1sSjd5VW0wdGIrUGtNCkpSdno0RFYxNGhQTkVxS2UzMjhu
            OWZSWHRMalRUaytZUGVnejRsS1NFUEkKLS0tIGNPL0F0amFLcCt2bXhxN0VtTVFD
            VFJIOGtNVVRjMkpSQXhGY3BSV20wZU0K+4gYdTFJ0mkR4Z4CgDl+By2lOYXQt5XT
            WxaRGudd3HF8VVcB6aYshIAHMq6yCdwyKM+caMImgmUPOAeT4IDRmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1huxz79cghdf0ewq6mq78pu3wuzyfhdr8qlw45tlqt74xrqt6t3es8k0zw0
    lastmodified: "2026-07-03T00:12:36Z"
    mac: ENC[AES256_GCM,data:xJkBNSt81VQuBENz2XtPMNV5d/YEHgerEba2B9Fopbq4ZCpDjhdU4iLKJy7jOR+ZEF1r7a3E47YZaZzbzDxT2JMS9qk3UNBO+F+QQ+gOxbTEkH/aor3vkLqJXhwHorN/HuMMGRuqrVCiFjFS0R4ybRYU0tBQWCb11Lp0RgudNGE=,iv:jdxPiok0fbKetIzC7fICWGo4QWDF5S6w48TeMD3B/qI=,tag:JkhVQ7V8JzMp+y1gCJChdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
