cloudflared:
    tunnelId: ENC[AES256_GCM,data:cekERPg8gIlyQtgJo1Y/O3Yx9rmYuNb7CE2A7T67HuPwrCoE,iv:v5mFVDqtcQLkAf0QuTDBtT8al+4fOwrTw/YZiHNBzMs=,tag:2tPfqIC9KSrbxZaELBYGqg==,type:str]
    credentialsJson: ENC[AES256_GCM,data:M7yVF8Qpg4seBI6f/005fy1/D9yEutWpQDprcL7TNT1W9wepUX4zEn7JMmJ57LaNCrKjfkgPIIeDDJeumrN06QRVUdWViArcpIPjHF06mJvtvrQC7kHk9YXsG/BraT0wLRICMoVLPrYG9ueGs6L8hqi2LX4oBYxlRRB8VFlSTRjm4IYJQUkQZKB41uSnQs2PRwEDNFVNUeD/trZthU0t36YHo1dixGOkH+2mE6y+Ew==,iv:onX8kglhemOfen3wUf/kIL9P0K5x112wmr9OPBoYFN4=,tag:WdezL/EENljqbYaAkFu2Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSEw4STVSb0Y2RVFjdTl1
            ajNuemZsalB2Yk9wVWExbGxCTW85RXI4QkFjCndoa0FKeFQ1L2djcUdLZFVLbHhT
            Y2t1ZGtCd0hQaytpUWx6aEwwTS9VMGMKLS0tIGV0L3pJU1hPWFJPU1kwT2dObWtT
            OFN0N3JncjhmZ1kwTkFnUTJtY010aXcK24r8kjqQT8yEOxW+5dIP2ph8cKpfrZyl
            CqShGXtDazYwkM4IqfGFi+2gYZXeI8LPe00e28f0oKX3yKWGU4T4pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1huxz79cghdf0ewq6mq78pu3wuzyfhdr8qlw45tlqt74xrqt6t3es8k0zw0
    lastmodified: "2026-07-12T23:20:38Z"
    mac: ENC[AES256_GCM,data:XjvOEueyilIOrGpimAdr8CaKvvwELDn4U/DBHXhspDIXSxO9pSgeCWty2Dm1jk1pieQ6PaB/UO18BR95a+K3FCvTo8I3IGFcboT5ckynS7CuB5wchXqCq2Anuh0TEEewhSjlhvVMsECT4c++RfdG1pLw8W9VcFHPYx6aznzYLMY=,iv:wStf1kLG0lbYAL2VSFWa4meEBWpz5LdqF9TDAHGjy4I=,tag:7lZMKrWo/MuJjjbb9MAudQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
