apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Release.Name }}
data:
  {{- $auth := printf "%s:%s" .Values.username .Values.password | b64enc }}
  {{- $dockerConfig := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.server .Values.username .Values.password $auth }}
  .dockerconfigjson: {{ $dockerConfig | b64enc }}