cloudflared:
    tunnelId: ENC[AES256_GCM,data:kVkZr3KvQohEBylox5QoT7JuE2ojyzzFK0W2yYeUhLxao2Dm,iv:TE3iA7blLxjVhl6FchgNvnw/XlE7cGGEwGeSlbIAfHA=,tag:seDqoFaS78gO0v/fix1w0g==,type:str]
    credentialsJson: ENC[AES256_GCM,data:33zQfjSaBlN5MmV731MzVm7Om4vkGnRvoPBzCAZPTJznNbErQyzA31uTDwg5iRE6SQIhlK1hqCyg3euZw0ZVANuYjy9wnRIMjR/SFvX5nuDIIFVhPyuHXSGyOw9btQkiPxNvl3fME0IitCuzHhPBPrU4jtT9sTj+DPCBu2h6ji+XVxTPlsx+sdNIrdSO5gTHA6tZaBQmkRwvODf6hyQpRr49BtVEqNyylPhS9+VNzw==,iv:IDHIdLFX6lWNdZgrl22ERK16lyLb1Iygq97OpfjkMjY=,tag:U/wWjq0L87t9QIAzPzRjqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNmRlb2ZZU1RyWDFuUi9k
            OG9jbUJCU0FFYkpnSkJqZjFoZFFmc3FTL2pzCnFSdnU1NzU5cVczWnZseGpiNWFs
            R2dKbnVBb0UvalYvSTE2T1BKWE0xUzQKLS0tIGZ1TDV2djk3MktLanJrQngzVy9U
            aFdFOUExM3hORVJSUGpmSkViN21LQkEKK7dM+4K7KUIfW4+aWeX0bzqDmQoWqdcP
            PLD5L26hg3l6H7hA3E2ZfzGfRWZ3DYL6LvFgIGLyZoJRzxOhCPrH8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1huxz79cghdf0ewq6mq78pu3wuzyfhdr8qlw45tlqt74xrqt6t3es8k0zw0
    lastmodified: "2026-07-12T23:41:41Z"
    mac: ENC[AES256_GCM,data:+CBryjpq6LbQNLK2zjPusoa4RC4EEq3ejO+3gVT1YgytuR2Fxe7Jxlf5AwWJNZL/RQFvsWBxqthpqXs/APmPgh0v/DeJketvfSLVH8qDX6y+ziU/70QSYSNXt04qkG8kelLWf2/iFLGHs9vMw1xru9oTFBavBBh/9pH7246B54o=,iv:HKtFCt7uj9w6iBFK8OJZNtoC6F/mVmC78clwqD+/OXA=,tag:Ovjgtl/IhLXnT+llvQ8NIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
